services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: dbob16
      POSTGRES_USER: tam4
      POSTGRES_DB: tam4
    command: postgres -c 'max_connections=200'

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
